TEXT_BASE = 0x23f00000
PLATFORM_CPPFLAGS += -mlittle-endian \
	-D__BYTE_ORDER=__LITTLE_ENDIAN \
	-D__BYTE_ORDER_BITFIELD=__LITTLE_ENDIAN_BITFIELD \
	-D__LITTLE_ENDIAN_BITFIELD -Werror
CONFIG_UIP_STACK_SUPPORT = y
CONFIG_UIP_STACK_SUPPORT = y
CONFIG_UIP_STACK_SUPPORT = y
